config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home', as: :home
  get 'about_us', to: 'pages#about_us', as: :about_us
  get 'our_data', to: 'pages#our_data', as: :our_data
  get 'hall_of_fame', to: 'pages#hall_of_fame', as: :hall_of_fame
  get 'resources/candidates', to: 'pages#candidates'
  get 'resources/apprentices', to: 'pages#apprentices'
  get 'resources/employers', to: 'pages#employers'
  get 'resources/educators', to: 'pages#educators'
  get 'apply_now', to: 'pages#apply_now', as: :apply_now
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#server_error'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
    @team_members = [
      {name: "Lyn Muldrow", img_url: "https://i.imgur.com/TWFrhpM.jpg", job: "Senior Developer Educator", company: "at DigitalOcean", location: "Atlanta, GA"},
      {name: "Kam Klauschie", img_url: "https://i.imgur.com/XZQLbYh.jpg", job: "Front End Engineer + Career Advisor", company: "at Pathrise", location: "Rio de Janeiro, Brazil"},
      {name: "Amelia Padua", img_url: "https://i.imgur.com/PM3nEsv.jpg", job: "Software Engineer", company: "at Pixavo", location: "Chicago, IL" },
      {name: "Marcos Cannabrava", img_url: "https://i.imgur.com/WcCT27g.jpg", job: "Co-Founder & Lead Developer", company: "at CareConsult", location: "Rio de Janeiro, Brazil"},
    ]
  end

  def our_data
    @total_aprnts,
    @total_companies,
    aprnts_gt_4_degree,
    aprnts_bootcamp,
    aprnts_per_prev_career,
    aprnts_ugi,
    aprnts_uri,
    @aprnts_to_fte,
    companies_per_employee,
    aprnts_per_co = CalcAirtableStatsJob.perform_now

    @perc_aprnts_gt_4_degree = ((aprnts_gt_4_degree.to_f/@total_aprnts)*100).round
    @perc_aprnts_bootcamp = ((aprnts_bootcamp.to_f/@total_aprnts)*100).round
    @perc_aprnts_ugi = ((aprnts_ugi.to_f/@total_aprnts)*100).round
    @perc_aprnts_uri = ((aprnts_uri.to_f/@total_aprnts)*100).round

    @top_five_prev_careers = aprnts_per_prev_career.select { |k, v| !k.nil? }
      .sort_by { |k, v| -v }.first(5).map {|item| item[0]}.join(", ")

    @aprnts_per_prev_career = aprnts_per_prev_career

    @co_most_apprentices_tracked = aprnts_per_co.sort_by { |k, v| -v }.first

    @companies_per_employee = companies_per_employee.sort_by { |k, v| -v }

    stats = StatsCalculator.new
    @companies_gt_100_employees = stats.get_companies_gt_100_employees

  end

  def hall_of_fame
  end

  def candidates
  end

  def apprentices
  end

  def employers
  end

  def educators
  end

  def apply_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/stats_calculator.rb
class StatsCalculator
  def initialize
    @companies_gt_100_employees = {
      'San Francisco' => 4434,
      'New York City' => 3010,
      'Washington DC' => 2031,
      'Chicago' => 1022,
      'Seattle' => 957,
      'Houston' => 912,
      'Atlanta' => 739,
      'Los Angeles' => 708,
      'Dallas' => 595,
      'Austin' => 568,
      'Boston' => 568,
      'Minneapolis' => 357,
      'Denver' => 347,
      'Miami' => 329
    }
  end
  def get_companies_gt_100_employees
     return @companies_gt_100_employees
  end
end

app/views/shared/_about.html.erb
<div class="mission-title">
  Our Mission
</div>
<div class="mission-loop">
</div>
<div class="mission-container d-none d-lg-block">
  <div class="mission">
    <center>
    We gather past, present, and future software engineering apprentices, and the employers and educators who love them.
    We advocate, empower, and create transparency around software engineering apprenticeships in the US in order to expand access and extend opportunity to software engineers from non-traditional education paths like bootcamps, community colleges, online programs, and self-directed study.
    We believe apprenticeships are a powerful tool to unlock human potential and to dismantle archaic, harmful beliefs in software engineering.
    </center>
  </div>
</div>
<div class="mission-loop-2 d-none d-lg-block">
</div>
<div class="purpose-container">
  <div class="purpose">
    tl;dr <br>
    We are working to make apprenticeships<br> tech industry standard in the United States. <br>
    <div class="emojis">
      🎉 🔧 💡
    </div>
  </div>
</div>
<div class="purpose-loop d-none d-lg-block">
</div>
<div class="team-title">
  Our Team
</div>
<div class= "team-loop d-none d-lg-block">
</div>
<div class= "team-member-container">
  <center>
  <%= render "shared/team_cards/lyn" %>
  <%= render "shared/team_cards/amelia" %>
  <%= render "shared/team_cards/marcos" %>
  <%= render "shared/team_cards/kam" %>
  </center>
</div>
<div class= "team-loop-2 d-none d-lg-block">
</div>
<div class="supporters-title d-none d-lg-block">
Our Supporters
</div>
<div class= "supporters-loop d-none d-lg-block">
</div>
  <div class= "supporters-container d-none d-lg-block">
  <center>
  <%= render "shared/team_cards/sar" %>
  <%= render "shared/team_cards/anthony" %>
  <%= render "shared/team_cards/dave" %>
  <%= render "shared/team_cards/joe" %>
  <%= render "shared/team_cards/katie" %>
  <%= render "shared/team_cards/maren" %>
  <%= render "shared/team_cards/jenn" %>
  <%= render "shared/team_cards/zara" %>
    </center>
  </div>
<div class= "supporters-loop-2 d-none d-lg-block">
</div>
<div class= "story-loop d-none d-lg-block">
</div>
<div class="story-container d-none d-lg-block">
<div class="story-title">
Our Story
</div>
<div class="story">
<center>
This project and community was originally inspired and created by a group of talented, caring Dev Bootcamp and Learner's Guild staff, students, and alumni in San Francisco and Oakland. When we started dreaming up this project in the fall of 2017, there were very few opportunities that welcomed and celebrated non-traditional education backgrounds in tech.<br><br>
We wanted to show companies that hiring non-traditional engineers through apprenticeship is valuable, affordable, and simple.  We wanted to dream about educational equity and envision what the tech industry could become.<br><br>
During COVID-19, we've been inspired to re-commit to this work with a new sense of importance and dedication. Today, we continue this work through advocacy, transparency, and empowerment across the United States.<br><br>
</center>
</div>
</div>
<div class= "story-loop-2 d-none d-lg-block">
</div>
<div class= "inspiration-loop d-none d-lg-block">
</div>
<div class="inspiration-container">
  <div class="inspiration-title">
  Our Inspiration
  </div>
  <div class="inspiration">
  Here are a few resources that inspire our work and our thinking. We're grateful to the people and organizations involved in creating these blogs, books, documentaries, websites, and more!
  </div>
  <div class= "inspiration-loop-2 d-none d-lg-block">
  </div>
</div>
<div class="inspiration-card-container">
  <center>
  <%= render "shared/inspiration_cards/apprentice_at" %>
  <%= render "shared/inspiration_cards/apprenticeship_patterns" %>
  <%= render "shared/inspiration_cards/associate_engineer_playbook" %>
  <%= render "shared/inspiration_cards/apprenticeships_me" %>
  <%= render "shared/inspiration_cards/revelry_apprenticeship_guide" %>
  <%= render "shared/inspiration_cards/chicago_apprenticeships" %>
  <%= render "shared/inspiration_cards/thoughtbot_apprenticeship_playbook" %>
  <%= render "shared/inspiration_cards/fail_state" %>
  <%= render "shared/inspiration_cards/lower_ed" %>
  </center>
  <div class= "inspiration-loop-3 d-none d-lg-block">
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="section section--featured">
    <div class="hero">
      <h1>For the love of non-traditional software engineers</h1>
      <h2>The largest community for software engineering apprenticeships in the United States</h2>
    </div>

    <!-- Thoughtbot Card https://i.imgur.com/dt2qqTZ.jpg -->
    <!-- Non-Visible Card -->
  <div class="d-none d-lg-block">
    <div class="row">
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/dt2qqTZ.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Non-Visible Card -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/dt2qqTZ.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Non-Visible Card -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/dt2qqTZ.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Non-Visible Card -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/dt2qqTZ.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Lyft Semi-Visible Top Left Card -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/GkpinWU.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Twilio Full Visible Top Right Card  -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="https://open.spotify.com/episode/5lvmN0oZsvxarc668ebhAo?si=jA-45AcVSBGyypxYgE7ehQ" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/P9YcCKR.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Microsoft Semi Visible Top Left Card Card  -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/e7AN3On.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Intuit Full Visible Middle Right Card  -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="https://open.spotify.com/episode/5n22Lp4m4QMIyO6216xUXg?si=UsUxpLTiRUeOLbwhqeo9WA" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/FcJeND3.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Slack Full Visible Front Left Card -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="https://www.theatlantic.com/technology/archive/2019/12/from-prison-to-silicon-valley/603406/" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/QKIUMzc.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- LinkedIn Full Visible Front Right Card -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="https://open.spotify.com/episode/3vzvIQVecjBsMYRTezcEMq?si=AMP_ZaWJQra0M9khXPlyyQ" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/UTYb1On.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>
      <!-- Uber Full Visible Front Right Card -->
      <div class="column">
        <div class="ItemCard">
          <a class="ItemCard__dest cover" href="https://open.spotify.com/episode/7s54IYY4C2QUbaQekOg4TA?si=mAXe2wIyQ4-6FExpiAKW7w" target="_blank"></a>
          <figure class="ItemCard__thumb">
            <img src="https://i.imgur.com/jRzQJ5f.jpg" height="340" width="510" alt="">
            <span class="shadow cover"></span>
          </figure>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="apprentice">
  <img class="apprentice-profile-img" src="https://i.imgur.com/RofeqbT.jpg" alt="">
  <div class="apprentice-description-bk"></div>
  <div class="apprentice-logo">
    <img src="https://www.authormedia.com/wp-content/uploads/2013/04/pinterest_badge_red.png" style="background:white" alt="Company Logo">
  </div>
  <div class="apprentice-name">
    <p> Zara Aslam</p>
  </div>
  <div  class="apprentice-info">
    <p>Former IT Network Engineer</p>
    <p> Dev Bootcamp</p>
    <p>San Francisco, CA</p>
  </div>
  <div class="apprentice-btn">
    <a href="#">Learn More</a>
  </div>
</div>

<!-- LinkedIn Logo: https://i.imgur.com/aua7Y0a.jpg -->

app/views/shared/_divider.html.erb
<div class="divider">
  <div class="slack-signup">
    <i id="divider-slack" class="fab fa-slack"></i>
    <a class="slack-signup-button" href="https://kamrinklauschie633721.typeform.com/to/GX7D6ek7"> Join Our Slack</a>
  </div>
  <div class="mailchimp-signup">
    <i id="divider-mailchimp" class="fab fa-mailchimp"></i>
    <form action="https://apprenticeship.us12.list-manage.com/subscribe/post?u=b6d580a0655273a98055e58d4&amp;id=5347c9d792" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email Address" required>
          <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_b6d580a0655273a98055e58d4_5347c9d792" tabindex="-1" value=""></div>
          <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="mailchimp-signup-button"></div>
    </form>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
<!--     <a href=""><i class="fab fa-slack"></i></a> -->
    <a href="https://github.com/apprenticeshipio"><i class="grow fab fa-github"></i></a>
    <a href="https://www.facebook.com/apprenticeshipio"><i class="grow fab fa-facebook"></i></a>
    <a href="https://twitter.com/kamrinklauschie"><i class="grow fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/company/18316521/admin/"><i class="grow fab fa-linkedin"></i></a>
    <a href="https://open.spotify.com/show/6oU6l4AjnVx2XD7HQeeOcg"><i class="grow fab fa-spotify"></i></a>
    <a href="https://medium.com/apprenticeship-io"><i class="grow fab fa-medium"></i></a>
    <a href="https://podcasts.apple.com/us/podcast/the-apprenticeship-io-podcast/id1452457373"><i class="grow fas fa-podcast"></i></a>
<!--     <a href=""><i class="fab fa-mailchimp"></i></a> -->
  </div>
  <div class="footer-mission d-none d-lg-block">
    Making apprenticeships tech industry standard.  🎉 🔧 💡
      <div class="footer-copyright">
        ©2017-2020 Kamrin Klauschie
      </div>
  </div>
</div>

app/views/shared/_hof_card.erb
<div class="apprentice">
  <img class="apprentice-profile-img" src="https://i.imgur.com/RofeqbT.jpg" alt="">
  <div class="apprentice-description-bk-purple"></div>
  <div class="apprentice-logo">
    <img src="https://i.imgur.com/JNdzqql.png" style="background:white" alt="Company Logo">
  </div>
  <div class="apprentice-name-extra-long">
    <p>Alexandra Wright</p>
  </div>
  <div  class="apprentice-info">
    <p>Former IT Network Engineer</p>
    <p>Flatiron School</p>
    <p>Oakland, CA</p>
  </div>
  <div class="apprentice-btn">
    <a href="#">Learn More</a>
  </div>
</div>

app/views/shared/_mini-banner.html.erb
      <% case type
        when "home-top"
          class_type = "mini-banner home-top d-none d-lg-block"
          img_top = ''
          h1_text = "What is an Apprenticeship?"
          p_text = "An apprenticeship is a 6 to 12 month (or longer!) paid training program aimed at developing mastery in specialized, high demand skills. Apprenticeships are hands-on, state of the art learning environments guided and supported by an advanced person of the trade or craft. You remember the Medieval blacksmiths? That's right, this path has been proven for over 500 years."
        when "home-bottom"
          class_type = "mini-banner home-bottom d-none d-lg-block"
          h1_text = "In the News"
          p_text = "Learn more about apprenticeships in technology happening all around the U.S."
          img_bottom = ""
        when "about-top"
          class_type = "mini-banner about-top d-none d-lg-block"
          h1_text = "About Us"
          p_text = "Learn more about the incredible team that builds and inspires our community."
        when "about-bottom"
          class_type = "mini-banner about-bottom d-none d-lg-block"
          h1_text = "Want to Join Forces?"
          p_text = "We are always looking to connect with folks who believe in apprenticeships."
          btn_text = "Let's Connect"
          btn_link = "mailto:kam@apprenticeship.io"
        when "hof-top"
          class_type = "mini-banner hof-top"
          h1_text = "Hall Of Fame"
          p_text = "It's time to get to know some of the amazing apprentices in software engineering around the United States."
        when "hof-bottom"
          class_type = "mini-banner hof-bottom"
          h1_text = "Know an Apprentice?"
          p_text = "We would love to hear from you if you or someone you know should be added to our community!"
          btn_text = "Nominate an Apprentice"
          btn_link = "mailto:kam@apprenticeship.io"
        when "apply-top"
          class_type = "mini-banner apply-top"
          h1_text = "Open Apprenticeships"
          p_text = "Find an apprenticeship for you and someone you love!"
        when "apply-bottom"
          class_type = "mini-banner apply-bottom"
          h1_text = "Know More Apprenticeships?"
          p_text = "We would love to hear from you if you know an apprenticeship we should add to our community!"
          btn_text = "Share a Program"
          btn_link = "mailto:kam@apprenticeship.io"
        when "candidates-top"
          class_type = "mini-banner candidates-top"
          h1_text = "For Candidates"
          p_text = "Learn more about apprenticeships and how to get hired!"
        when "candidates-bottom"
          class_type = "mini-banner candidates-bottom"
          h1_text = "Not Finding What You Need?"
          p_text = "Tell us what you're looking for to prepare!"
          btn_text = "Contact Us"
          btn_link = "mailto:kam@apprenticeship.io"
        when "apprentices-top"
          class_type = "mini-banner apprentices-top"
          h1_text = "For Apprentices"
          p_text = "Learn how to get the most out of your apprenticeship and connect with peers!"
        when "apprentices-bottom"
          class_type = "mini-banner apprentices-bottom"
          h1_text = "Not Finding What You Need?"
          p_text = "Tell us what you're looking for as you progress in your apprenticeship!"
          btn_text = "Contact Us"
          btn_link = "mailto:kam@apprenticeship.io"
        when "employers-top"
          class_type = "mini-banner employers-top"
          h1_text = "For Employers"
          p_text = "Find resources to start or expand your apprenticeship and connect with fellow employers!"
        when "employers-bottom"
          class_type = "mini-banner employers-bottom"
          h1_text = "Looking for More?"
          p_text = "We'd love to connect with you and chat!"
          btn_text = "Contact Us"
          btn_link = "mailto:kam@apprenticeship.io"
        when "educators-top"
          class_type = "mini-banner educators-top"
          h1_text = "For Educators"
          p_text = "Learn more about apprenticeships and discover resources to share with your students!"
        when "educators-bottom"
          class_type = "mini-banner educators-bottom"
          h1_text = "Looking for More?"
          p_text = "We'd love to connect with you and chat!"
          btn_text = "Contact Us"
          btn_link = "mailto:kam@apprenticeship.io"
      end %>
<div class="<%= class_type %>" style="">
  <div class="mini-container">
    <%if img_top %>
      <%= asset_path img_top %>
    <%end%>
    <h1>
      <%= h1_text %>
    </h1>
    <p>
      <%= p_text %>
    </p>
    <%if btn_text%>
      <a target="_blank" href=<%= btn_link %> class="mini-banner-btn">
        <%= btn_text %>
      </a>
    <%if img_bottom %>
      <img src=<%= img_top %> alt= <%= img_bottom_alt %> >
    <%end%>
    <%end%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="podcast-header align-items-center d-none d-sm-block">
  <div class="header-links">
<!--     <a href=""><i class="fab fa-slack"></i></a> -->
    <a href="https://github.com/apprenticeshipio"><i class="grow fab fa-github"></i></a>
    <a href="https://www.facebook.com/apprenticeshipio"><i class="grow fab fa-facebook"></i></a>
    <a href="https://twitter.com/kamrinklauschie"><i class="grow fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/company/18316521/admin/"><i class="grow fab fa-linkedin"></i></a>
    <a href="https://open.spotify.com/show/6oU6l4AjnVx2XD7HQeeOcg"><i class="grow fab fa-spotify"></i></a>
    <a href="https://medium.com/apprenticeship-io"><i class="grow fab fa-medium"></i></a>
    <a href="https://podcasts.apple.com/us/podcast/the-apprenticeship-io-podcast/id1452457373"><i class="grow fas fa-podcast"></i></a>
<!--     <a href=""><i class="fab fa-mailchimp"></i></a> -->
  </div>
</div>

<div class="navbar navbar-expand-sm navbar-apprenticeship">
  <a class="navbar-brand" href="/home">
    <img src="https://i.imgur.com/7VSA6VB.png" alt="apprenticeship.io Logo" />
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="collapsible" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "About Us", about_us_path, class: "nav-link" %>
      </li>
      <li class="nav-item d-none d-lg-block">
        <%= link_to "Our Data", our_data_path, class: "nav-link" %>
      </li>
      <li class="nav-item d-none d-lg-block">
        <%= link_to "Hall of Fame", hall_of_fame_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown d-none d-lg-block">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Resources</a>
          <div class="dropdown-menu dropdown-menu-right" >
          <%= link_to "For Apprentices", resources_apprentices_path, class: "dropdown-item" %>
          <%= link_to "For Employers", resources_employers_path, class: "dropdown-item" %>
          <a class="dropdown-item"> For Candidates <div class="coming-soon"> <i class="fas fa-wrench"></i> Coming Soon! </div> </a>
          <a class="dropdown-item"> For Educators <div class="coming-soon"> <i class="fas fa-wrench"></i> Coming Soon! </div> </a>
          <!-- link_to "For Candidates", resources_candidates_path, class: "dropdown-item" -->
          <!-- link_to "For Educators", resources_educators_path, class: "dropdown-item" -->
        </div>
      </li>
      <!-- <li class="nav-item-button"> -->
        <!-- link_to "Apply Now", apply_now_path, class: "btn btn-flat" -->
      <!-- </li> -->
    </ul>
  </div>
</div>

app/views/shared/_resources-card.html.erb
<div class="resources-card">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="resources-card-info">
    <h2>
      <% case type
        when "employer-1" %>
          Identifying Problems an Apprenticeship Can Solve
        <% when "employer-2" %>
          Finding an Apprenticeship Program Champion
        <% when "employer-3" %>
          Mobilizing Internal Advocates, Mentors, Sponsors, and Allies
        <% when "employer-4" %>
          Designing Your Company's Apprenticeship Program
        <% when "employer-5" %>
          Sourcing, Recruiting, & Building Apprenticeship Partners
        <% when "employer-6" %>
          Launching Your Company's Apprenticeship Program
      <% end %>
    </h2>
    <p>
      <% case type
        when "employer-1" %>
          Learn more about apprenticeships with this awesome article we wrote for you!
        <% when "employer-2" %>
          Learn more about apprenticeships with this awesome article we wrote for you!
        <% when "employer-3" %>
          Learn more about apprenticeships with this awesome article we wrote for you!
        <% when "employer-4" %>
          Learn more about apprenticeships with this awesome article we wrote for you!
        <% when "employer-5" %>
          Learn more about apprenticeships with this awesome article we wrote for you!
        <% when "employer-6" %>
          Learn more about apprenticeships with this awesome article we wrote for you!
      <% end %>
    </p>
  </div>
</div>

app/views/shared/principles_cards/_principles-card.html.erb
<div class="principle-card">
  <div  class="principle-info">
    <p> Dignity > Charity </p>
  </div>
</div>